<?php
/**
 * Plugin Name: Gulfino HTTPS Enforcer
 * Description: Forces all internal links and resources to use HTTPS.
 */

// Force HTTPS for all URLs generated by WordPress
add_filter('home_url', 'gulfino_force_https', 10, 2);
add_filter('site_url', 'gulfino_force_https', 10, 2);
add_filter('wp_get_attachment_url', 'gulfino_force_https', 10, 2);
add_filter('plugins_url', 'gulfino_force_https', 10, 2);
add_filter('theme_root_uri', 'gulfino_force_https', 10, 2);
add_filter('content_url', 'gulfino_force_https', 10, 2);
add_filter('script_loader_src', 'gulfino_force_https', 10, 2);
add_filter('style_loader_src', 'gulfino_force_https', 10, 2);

function gulfino_force_https($url) {
    // Skip for localhost
    if (strpos($_SERVER['HTTP_HOST'], 'localhost') !== false) {
        return $url;
    }
    if (is_string($url)) {
        return str_replace('http://', 'https://', $url);
    }
    return $url;
}

// Force redirect to HTTPS if not already on it
add_action('template_redirect', function() {
    // Skip for localhost
    if (strpos($_SERVER['HTTP_HOST'], 'localhost') !== false) {
        return;
    }
    if (!is_ssl() && !is_admin()) {
        if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            // Already on HTTPS via proxy, do nothing
            return;
        }
        wp_redirect('https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'], 301);
        exit();
    }
});
