name: Deploy to EasyWP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Remove non-deployable files before upload
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf scripts
          rm -rf wp-content/backups-dup-lite
          rm -f wp-config.php .env router.php

      - name: Sync Files to EasyWP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'gulfino-13d6bce'
          server: 'fs-alpha.easywp.com'
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: './'
          remote_path: './'
          sftp_only: true
          delete_remote_files: false
